name: Build KSE and run tests

on:
  pull_request:
    branches: [ main ]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: kse
    - name: Build with Gradle
      run: ./gradlew build test
      working-directory: kse

